data:
  batch_size: 512 #batch size during inference
  tr_batch_size: 128 # number of anchors to draw from the training data
                    # (from which "n_anchor" are selected at random)
  n_workers: 2

  in_dataset:
    cifar10: "/p/lustre1/anirudh1/delta/pytorch/classification/CIFAR/pytorch-cifar/data/"
    cifar100: "/p/lustre1/anirudh1/delta/pytorch/classification/CIFAR/pytorch-cifar/data/"

  ood_benchmark:
    svhn: "/p/lustre1/anirudh1/delta/pytorch/classification/CIFAR/pytorch-cifar/data/SVHN-dataset"
    imagenet_r: "/p/lustre1/anirudh1/delta/pytorch/classification/OOD/odin/data/Imagenet_resize/"
    imagenet: "/p/lustre1/anirudh1/delta/pytorch/classification/OOD/odin/data/Imagenet/"
    lsun: "/p/lustre1/anirudh1/delta/pytorch/classification/OOD/odin/data/LSUN/"
    lsun_r: "/p/lustre1/anirudh1/delta/pytorch/classification/OOD/odin/data/LSUN_resize/"
    texture:  "/usr/workspace/anirudh1/delUQ/data/images/texture/"
    places365:  "/usr/workspace/anirudh1/delUQ/data/images/places365"
    isun: "/p/lustre1/anirudh1/delta/pytorch/classification/OOD/odin/data/iSUN/"

  resizing_benchmark:
    bicubic:  "/usr/workspace/anirudh1/delUQ/LSUN_resize/pil/bicubic"
    bilinear: "/usr/workspace/anirudh1/delUQ/LSUN_resize/pil/bilinear"
    lanczos:  "/usr/workspace/anirudh1/delUQ/LSUN_resize/pil/lanczos"
    nearest:  "/usr/workspace/anirudh1/delUQ/LSUN_resize/pil/nearest"
    lsun_native:  "/usr/workspace/anirudh1/delUQ/data/images/lsun"

  scood_benchmark:
    root: "/usr/workspace/anirudh1/delUQ/data/"

models:
  ckpt_save: "./chkpts/"
  model_name: "ckpt-199.pth" #which model to load
  seeds: [1] #seeds to evaluate
