data:
  batch_size: 256 #batch size during inference
  tr_batch_size: 128 # number of anchors to draw from the training data
                    # (from which "n_anchor" are selected at random)
  n_workers: 2

  in_dataset:
    cifar10: "path-to-cifar10-data/"
    cifar100: "path-to-cifar100-data/"

  ood_benchmark:
    svhn: "path/ood/data"
    imagenet_r: "path/ood/data"
    imagenet: "path/ood/data"
    lsun: "path/ood/data"
    lsun_r: "path/ood/data"
    texture:  "path/ood/data"
    places365:  "path/ood/data"
    isun: "path/ood/data"

  resizing_benchmark:
    bicubic:  "resize_ood/bicubic"
    bilinear: "resize_ood/bilinear"
    lanczos:  "resize_ood/lanczos"
    nearest:  "resize_ood/nearest"
    lsun_native:  "path/to/original/lsun"

  scood_benchmark:
    root: "point/to/downloaded/scood/benchmark/here"

models:
  ckpt_save: "./chkpts/"
  model_name: "ckpt-199.pth" #which model to load
  seeds: [1] #seeds to evaluate
